name: CI

on: [push]

env:
  NEXT_PUBLIC_CONTENT_SEARCH_URL: https://cig-content-search-service.herokuapp.com/

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install yarn and dependencies
        run: |
          npm install -g yarn
          yarn
          yarn --check-files
      - name: Running tests
        run: |
          yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install yarn and dependencies
        run: |
          npm install -g yarn
          yarn
          yarn --check-files

      - name: Linter
        run: |
          yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install yarn and dependencies
        run: |
          npm install -g yarn
          yarn
          yarn --check-files

      - name: Build
        run: |
          yarn build
